import os
import yaml

posts_dir = '_posts'
for filename in os.listdir(posts_dir):
    if not (filename.endswith('.markdown') or filename.endswith('.md')):
        continue
        
    filepath = os.path.join(posts_dir, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    parts = content.split('---', 2)
    if len(parts) >= 3:
        fm = parts[1]
        
        # We can parse the yaml to get the excerpt, then rebuild the text
        try:
            parsed = yaml.safe_load(fm)
            excerpt = parsed.get('excerpt', '')
            
            # Remove any line breaks from the parsed excerpt just in case
            excerpt = " ".join(excerpt.split())
            
            # We want to replace the `excerpt: ...` block in fm with `excerpt: "..."`
            # Since the YAML was generated by Ruby's YAML.dump, we can just dump it with Python's yaml with width=float("inf")
            # Wait, let's just dump it with Python's yaml.
            
            # Or manually format:
            new_fm_lines = []
            for key, val in parsed.items():
                if key == 'excerpt':
                    new_fm_lines.append(f'excerpt: "{excerpt}"')
                elif key == 'tags':
                    new_fm_lines.append('tags:')
                    for t in val:
                        new_fm_lines.append(f'- {t}')
                else:
                    new_fm_lines.append(f'{key}: {val}')
            
            new_content = parts[0] + '---\n' + '\n'.join(new_fm_lines) + '\n---\n' + parts[2].lstrip('\n')
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
        except Exception as e:
            print(f"Error on {filename}: {e}")

